AZURE_LOCATION: 'USGov Texas'
RESOURCE_NAME_PREFIX: 'ase-demo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'byte-master'
CICD_AGENT_TYPE: 'azuredevops'
