AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'aa-johngal62'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'byte-master'
CICD_AGENT_TYPE: 'github'
