AZURE_LOCATION: 'usgovtexas'
RESOURCE_NAME_PREFIX: 'aa-johngal01'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment1'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'byte-master'
CICD_AGENT_TYPE: 'github'
